"""add avatar_url and synced_at to users

Revision ID: 4dfbaba4f5f5
Revises: f92a0c6c4572
Create Date: 2026-07-16 14:35:12.560375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4dfbaba4f5f5'
down_revision: Union[str, None] = 'f92a0c6c4572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'synced_at')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
