"""add dashboard layout to users

Revision ID: ea4194f80f45
Revises: 4dfbaba4f5f5
Create Date: 2026-07-23 12:44:34.712351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea4194f80f45'
down_revision: Union[str, None] = '4dfbaba4f5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dashboard_layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard_layout')
    # ### end Alembic commands ###
