"""add ticket type, recurring tickets, and comments

Revision ID: fd7c07032e4b
Revises: 57fd6c07817d
Create Date: 2026-07-11 12:24:27.081059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd7c07032e4b'
down_revision: Union[str, None] = '57fd6c07817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_ticket_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('recurrence_day', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default backfills existing rows for these NOT NULL columns;
    # dropped afterward so future values come from the ORM default only,
    # matching how the other columns on this table are handled.
    op.add_column(
        'tickets',
        sa.Column(
            'ticket_type', sa.String(), nullable=False,
            server_default=sa.text("'assigned'"),
        ),
    )
    op.add_column(
        'tickets',
        sa.Column(
            'is_recurring', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('tickets', sa.Column('recurrence_day', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'tickets_template_id_fkey', 'tickets', 'recurring_ticket_templates',
        ['template_id'], ['id'],
    )
    op.alter_column('tickets', 'ticket_type', server_default=None)
    op.alter_column('tickets', 'is_recurring', server_default=None)
    # ### end Alembic commands ###

    # Data migration: existing "open" tickets map to the new "to_do" status
    op.execute("UPDATE tickets SET status = 'to_do' WHERE status = 'open'")


def downgrade() -> None:
    # Reverse the data migration before the old status values go out of use
    op.execute("UPDATE tickets SET status = 'open' WHERE status = 'to_do'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_template_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'template_id')
    op.drop_column('tickets', 'recurrence_day')
    op.drop_column('tickets', 'is_recurring')
    op.drop_column('tickets', 'ticket_type')
    op.drop_table('ticket_comments')
    op.drop_table('recurring_ticket_templates')
    # ### end Alembic commands ###
